### ISSUE TITLE
TnH-9 Создать заготовку страницы "/about" 

### ISSUE THREAD

**Issue by mark-nikerin** [algorithm-ssau/Toast-n-Honey#11]
Согласно инструкции в задаче #4 необходимо создать заготовку для будущей страницы "/about"

1. Создать функцию, соответствующую роутингу "/about/"
2. Добавить соответствующий файл html, содержащий минимальную разметку

**Comment by eleonora-radina** [comment]
Страница About была удалена, вместо нее добавлена страница Десерты. Изменена страница контактов.
