### ISSUE TITLE
TnH-4 Продумать схему БД

### ISSUE THREAD

**Issue by mark-nikerin** [algorithm-ssau/Toast-n-Honey#6]
Нужно выделить основные сущности, определить связи между ними и необходимые ограничения, составить ER-диаграмму полученных отношений

**Comment by eleonora-radina** [comment]
Составлена схема базы данных. Прикрепляю во вложениях.

![db scheme](https://user-images.githubusercontent.com/61162413/77861890-8c80e980-7220-11ea-95af-8fdba2ae1116.jpg)
